name: Env Test
on: push 
env: 
  WF_ENV: Available to all jobs 

jobs:
  Deploy_Configure_Lambda: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Create LambdaFunction 
          run: |
            ls -la
            cd LambdaFunction
            zip -r ../TweetLoader2ZIP.zip .
            ls -la
            cd ../ 
            ls -la
            aws lambda create-function --function-name "TestLoader5" --runtime "python3.8" --role "arn:aws:iam::290544014146:role/LambdaRole" --zip-file "fileb://TweetLoader2ZIP.zip" --handler lambda_function.lambda_handler
            
        - name: Configure Environment
          run: | 
            aws lambda update-function-configuration --function-name TestLoader5 --environment  "Variables={BASELINE_FILE=2022-05-14-8.json.gz,BOOKMARK_FILE=bookmark,BUCKET_NAME=tweets-ingested,FODLER_PREFIX=landing/timeline,environment=dev,BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}}" --query "Environment"
            aws lambda update-function-configuration --function-name TestLoader5 --timeout 90 --memory-size 1024 
