name: Env Test
on: push 
env: 
  WF_ENV: Available to all jobs 

jobs:
  log-default-env: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Default ENV Variables 
          run: |
            ls -la
            cd LambdaFunction
            zip -r ../TweetLoader2ZIP.zip .
            ls -la
            cd ../ 
            ls -la
            aws lambda create-function --function-name "TestLoader4" --runtime "python3.8" --role "arn:aws:iam::290544014146:role/LambdaRole" --zip-file "fileb://TweetLoader2ZIP.zip" --handler lambda_function.lambda_handler
